linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false
    severity: error

  BemDepth:
    enabled: true
    max_elements: 1
    severity: error

  BorderZero:
    enabled: true
    convention: none
    severity: error

  ColorKeyword:
    enabled: false # revisit with palette functions
    severity: error

  ColorVariable:
    enabled: false # revisit with palette functions
    severity: error

  Comment:
    enabled: true
    severity: error

  Compass::*:
    enabled: false
    severity: error

  DebugStatement:
    enabled: true
    severity: error

  DeclarationOrder:
    enabled: true
    severity: error

  DuplicateProperty:
    enabled: true
    severity: error

  ElsePlacement:
    enabled: true
    style: same_line
    severity: error

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true
    severity: error

  EmptyRule:
    enabled: true
    severity: error

  ExtendDirective:
    enabled: true
    severity: error

  FinalNewline:
    enabled: true
    present: true
    severity: error

  HexLength:
    enabled: true
    style: long
    severity: warning

  HexNotation:
    enabled: true
    style: lowercase
    severity: error

  HexValidation:
    enabled: true
    severity: error

  IdSelector:
    enabled: true
    severity: error

  ImportantRule:
    enabled: true
    severity: error

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false
    severity: error

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 4
    severity: error

  LeadingZero:
    enabled: true
    style: include_zero
    severity: error

  MergeableSelector:
    enabled: true
    force_nesting: true
    severity: error

  NameFormat:
    enabled: true
    allow_leading_underscore: false
    convention: hyphenated_lowercase
    severity: error

  NestingDepth:
    enabled: true
    max_depth: 5
    ignore_parent_selectors: false
    severity: error

  PlaceholderInExtend:
    enabled: true
    severity: error

  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10
    severity: error

  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    min_properties: 2
    order: concentric
    separate_groups: false
    severity: error

  PropertySpelling:
    enabled: true
    extra_properties: []
    severity: error

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties:
      line-height: []
    severity: error

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: false
    allow_element_with_id: false
    severity: error

  SelectorDepth:
    enabled: true
    max_depth: 3
    severity: error

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    severity: error

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3]
    severity: error

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false
    severity: error

  SingleLinePerSelector:
    enabled: true
    severity: error

  SpaceAfterComma:
    enabled: true
    severity: error

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space_or_newline
    severity: error

  SpaceAfterPropertyName:
    enabled: true
    severity: error

  SpaceAroundOperator:
    enabled: true
    severity: error

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false
    severity: error

  SpaceBetweenParens:
    enabled: true
    spaces: 0
    severity: error

  StringQuotes:
    enabled: true
    style: single_quotes
    severity: error

  TrailingSemicolon:
    enabled: true
    severity: error

  TrailingWhitespace:
    enabled: true
    severity: error

  TrailingZero:
    enabled: true
    severity: error

  UnnecessaryMantissa:
    enabled: true
    severity: error

  UnnecessaryParentReference:
    enabled: true
    severity: error

  UrlFormat:
    enabled: true
    severity: error

  UrlQuotes:
    enabled: true
    severity: error

  VariableForProperty:
    enabled: false
    properties: []
    severity: error

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []
    severity: error

  ZeroUnit:
    enabled: true
    severity: error
